// user
export const USER_SET_USER_TOKEN = 'USER_SET_USER_TOKEN'
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO'
export const USER_RESET_USER = 'USER_RESET_USER'

// app
export const SET_COLLAPSED = 'SET_COLLAPSED'
